# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baidu-api.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from cnocr import CnOcr
import cv2
import numpy as np


def cv_imread(file_path):
    cv_img = cv2.imdecode(np.fromfile(file_path, dtype=np.uint8), cv2.IMREAD_COLOR)
    return cv_img

imgurl = r"C:\Users\1212214\Desktop\中文\中文.jpg"
new_ = cv_imread(imgurl)
ocr = CnOcr()  # 所有参数都使用默认值
result = ocr.ocr(new_, cls=True)
txts = [line['text'] for line in result]  # Nested loop added
# result = ocr.ocr(img_path, cls=True)
print(txts)

