# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baidu-api.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from sqlalchemy import create_engine
engine = create_engine("mysql://root:root@localhost:3306/kg?charset=utf8")
con = engine.connect()